// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Telerik.iOS
{
	public partial class SwitchTableViewCell : UITableViewCell
	{
		public SwitchTableViewCell (IntPtr handle) : base (handle)
		{
            
		}

        public void SetLabel(string theText)
        {
            switchLabel.Text = theText;
        }
	}
}
